import { put, type PutBlobResult } from "@vercel/blob";

/**
 * Thin wrapper around @vercel/blob for the two artifacts we store:
 * signed JV agreement PDFs (from PandaDoc / Jotform) and setter-uploaded
 * attachments (M5). Wraps `put()` with conventions for naming + access.
 *
 * Access mode: the jvwithniche-blob store is configured as `private`,
 * so uploads must specify access: "private". Served via signed URLs
 * generated by Vercel Blob's @vercel/blob/client.get(). Admin downloads
 * proxy through our server so we control auth.
 */

export async function uploadSignedPdf({
  submissionId,
  pdf,
  provider,
}: {
  submissionId: string;
  pdf: Blob;
  provider: "pandadoc" | "jotform";
}): Promise<PutBlobResult> {
  const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
  const pathname = `submissions/${submissionId}/jv-agreement__${provider}__${timestamp}.pdf`;

  return put(pathname, pdf, {
    access: "private",
    contentType: "application/pdf",
    // Keep the filename stable for admin downloads.
    addRandomSuffix: false,
    // Long cache because the PDF content is immutable once written.
    cacheControlMaxAge: 60 * 60 * 24 * 365,
  });
}

/**
 * Upload a follow-up attachment that a JV partner added via the /view
 * portal. Paths are namespaced by submission + update id so collisions
 * are impossible and admins can see every file for a given JV in one
 * prefix.
 */
export async function uploadJvAttachment({
  submissionId,
  updateId,
  file,
  filename,
  contentType,
}: {
  submissionId: string;
  updateId: string;
  file: Blob | ArrayBuffer | Uint8Array;
  filename: string;
  contentType: string;
}): Promise<PutBlobResult> {
  const safeName = filename.replace(/[^a-zA-Z0-9._-]+/g, "-").slice(0, 160);
  const pathname = `submissions/${submissionId}/attachments/${updateId}/${safeName}`;
  return put(pathname, file as Blob, {
    access: "private",
    contentType,
    addRandomSuffix: false,
    cacheControlMaxAge: 60 * 60 * 24 * 365,
  });
}
